// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v6.30.2
// source: plannig.proto

package pbs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvailabilityInquiryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Equipment int64  `protobuf:"varint,1,opt,name=equipment,proto3" json:"equipment,omitempty"`
	Quantity  int64  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	StartAt   string `protobuf:"bytes,3,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt     string `protobuf:"bytes,4,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
}

func (x *AvailabilityInquiryRequest) Reset() {
	*x = AvailabilityInquiryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plannig_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailabilityInquiryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityInquiryRequest) ProtoMessage() {}

func (x *AvailabilityInquiryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plannig_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityInquiryRequest.ProtoReflect.Descriptor instead.
func (*AvailabilityInquiryRequest) Descriptor() ([]byte, []int) {
	return file_plannig_proto_rawDescGZIP(), []int{0}
}

func (x *AvailabilityInquiryRequest) GetEquipment() int64 {
	if x != nil {
		return x.Equipment
	}
	return 0
}

func (x *AvailabilityInquiryRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AvailabilityInquiryRequest) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *AvailabilityInquiryRequest) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

type AvailabilityInquiryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAvailable bool `protobuf:"varint,1,opt,name=IsAvailable,proto3" json:"IsAvailable,omitempty"`
}

func (x *AvailabilityInquiryResponse) Reset() {
	*x = AvailabilityInquiryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plannig_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailabilityInquiryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityInquiryResponse) ProtoMessage() {}

func (x *AvailabilityInquiryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plannig_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityInquiryResponse.ProtoReflect.Descriptor instead.
func (*AvailabilityInquiryResponse) Descriptor() ([]byte, []int) {
	return file_plannig_proto_rawDescGZIP(), []int{1}
}

func (x *AvailabilityInquiryResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type GetShortagesInquiryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartAt string `protobuf:"bytes,1,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt   string `protobuf:"bytes,2,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
}

func (x *GetShortagesInquiryRequest) Reset() {
	*x = GetShortagesInquiryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plannig_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShortagesInquiryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortagesInquiryRequest) ProtoMessage() {}

func (x *GetShortagesInquiryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plannig_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortagesInquiryRequest.ProtoReflect.Descriptor instead.
func (*GetShortagesInquiryRequest) Descriptor() ([]byte, []int) {
	return file_plannig_proto_rawDescGZIP(), []int{2}
}

func (x *GetShortagesInquiryRequest) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *GetShortagesInquiryRequest) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

type GetShortagesInquiryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shortages map[int64]int64 `protobuf:"bytes,1,rep,name=shortages,proto3" json:"shortages,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *GetShortagesInquiryResponse) Reset() {
	*x = GetShortagesInquiryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plannig_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShortagesInquiryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortagesInquiryResponse) ProtoMessage() {}

func (x *GetShortagesInquiryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plannig_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortagesInquiryResponse.ProtoReflect.Descriptor instead.
func (*GetShortagesInquiryResponse) Descriptor() ([]byte, []int) {
	return file_plannig_proto_rawDescGZIP(), []int{3}
}

func (x *GetShortagesInquiryResponse) GetShortages() map[int64]int64 {
	if x != nil {
		return x.Shortages
	}
	return nil
}

var File_plannig_proto protoreflect.FileDescriptor

var file_plannig_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x88, 0x01, 0x0a, 0x1a, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6e, 0x64, 0x41, 0x74, 0x22, 0x3f, 0x0a, 0x1b, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x49, 0x73, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x4e, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x61, 0x67, 0x65, 0x73, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x15,
	0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6e, 0x64, 0x41, 0x74, 0x22, 0xaf, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x61, 0x67, 0x65, 0x73, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x61, 0x67, 0x65, 0x73,
	0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x61, 0x67, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x3c, 0x0a, 0x0e, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x61, 0x67, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xca, 0x01, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x0b, 0x49,
	0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x24, 0x2e, 0x70, 0x6c, 0x61,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x61, 0x67, 0x65, 0x73, 0x12, 0x24, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x61, 0x67, 0x65, 0x73, 0x49,
	0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x61, 0x67, 0x65, 0x73, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plannig_proto_rawDescOnce sync.Once
	file_plannig_proto_rawDescData = file_plannig_proto_rawDesc
)

func file_plannig_proto_rawDescGZIP() []byte {
	file_plannig_proto_rawDescOnce.Do(func() {
		file_plannig_proto_rawDescData = protoimpl.X.CompressGZIP(file_plannig_proto_rawDescData)
	})
	return file_plannig_proto_rawDescData
}

var file_plannig_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_plannig_proto_goTypes = []interface{}{
	(*AvailabilityInquiryRequest)(nil),  // 0: planning.AvailabilityInquiryRequest
	(*AvailabilityInquiryResponse)(nil), // 1: planning.AvailabilityInquiryResponse
	(*GetShortagesInquiryRequest)(nil),  // 2: planning.GetShortagesInquiryRequest
	(*GetShortagesInquiryResponse)(nil), // 3: planning.GetShortagesInquiryResponse
	nil,                                 // 4: planning.GetShortagesInquiryResponse.ShortagesEntry
}
var file_plannig_proto_depIdxs = []int32{
	4, // 0: planning.GetShortagesInquiryResponse.shortages:type_name -> planning.GetShortagesInquiryResponse.ShortagesEntry
	0, // 1: planning.PlanningService.IsAvailable:input_type -> planning.AvailabilityInquiryRequest
	2, // 2: planning.PlanningService.GetShortages:input_type -> planning.GetShortagesInquiryRequest
	1, // 3: planning.PlanningService.IsAvailable:output_type -> planning.AvailabilityInquiryResponse
	3, // 4: planning.PlanningService.GetShortages:output_type -> planning.GetShortagesInquiryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plannig_proto_init() }
func file_plannig_proto_init() {
	if File_plannig_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plannig_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailabilityInquiryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plannig_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailabilityInquiryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plannig_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShortagesInquiryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plannig_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShortagesInquiryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plannig_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plannig_proto_goTypes,
		DependencyIndexes: file_plannig_proto_depIdxs,
		MessageInfos:      file_plannig_proto_msgTypes,
	}.Build()
	File_plannig_proto = out.File
	file_plannig_proto_rawDesc = nil
	file_plannig_proto_goTypes = nil
	file_plannig_proto_depIdxs = nil
}
